target-version = "py310"

[lint]
select = [
    "E", # pycodestyle
    "F", # pyflakes
    "B", # flake8-bugbear
    "I", # isort
    "D", # pydocstyle
    "UP", # pyupgrade
]

# Ignored rules
# - E501: line-too-long
# - I001: unsorted-imports
# - D205: blank-line-after-summary
# - D402: no-signature
# - D415: ends-in-punctuation
# - D417: undocumented-param
ignore = ["E501", "I001", "D205", "D402", "D415", "D417"]

# Avoid trying to fix flake8-bugbear (`B`) violations.
unfixable = ["B"]

# Ignore E402 (unused import)
[lint.per-file-ignores]
"patoolib/programs/*.py" = ["E402"]

[lint.isort]
known-first-party = ["patoolib"]
section-order = ["future", "standard-library", "third-party", "first-party", "local-folder"]
force-sort-within-sections = false

[lint.pydocstyle]
convention = "google"
