[project]
name = "patool"
version = "3.1.1"
requires-python = ">=3.10"
dependencies = ["security==1.3.1"]
# these values are set by setup.py
dynamic = ["scripts", "authors", "keywords", "classifiers", "urls", "license", "readme", "description"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
# these modules are only needed for development

[project.optional-dependencies]
# optional features
argcompletion = [
  'argcomplete==3.5.1',
]

[tool.uv]
dev-dependencies = [
  # for using setuptools.setup() in setup.py
  "setuptools==75.6.0",

  # for testing
  "pytest==8.3.4",
  # plugin to run tests in parallel
  "pytest-xdist[psutil]==3.6.1",
  # plugin to run tests in random order
  "pytest-randomly==3.16.0",

  # for python code linting
  "ruff==0.8.1",

  # for python type checking
  "pytype==2024.10.11",

  # for generating a Python .whl file
  "wheel==0.45.1",

  # for generating the web page
  "sphinx==8.1.3",
  "myst-parser==4.0.0",

  # for upgrading the version number
  "bump2version==1.0.1",

  # test optional functionality
  "patool[argcompletion]",
]

[tool.patool]
# pin versions of Python and uv for development
python_version_dev = "3.12.7"
uv_version_dev = "0.5.6"
